### ISSUE TITLE
implement triangular matrix parsing for unlabeled 

### ISSUE THREAD

**Issue by fkaiserbio** [singa-bio/singa#61]
- as done for labeled matrices, parsing from CSV should also work for unlabeled matrices

**Comment by cleberecht** [comment]
@fkaiserbio 
I think this is actually implemented (see readUnlabeledMatrixFromCSV in the Matrices class)?
Could probably closed.

**Comment by fkaiserbio** [comment]
- confirm on that, thanks for checking
