### ISSUE TITLE
SmilesParser fails to parse simple smiles

### ISSUE THREAD

**Issue by fkaiserbio** [singa-bio/singa#85]
- parsing of the SMILES string **CC(=O)N(C)C** produces a NPE, but works on PubChem website: https://pubchem.ncbi.nlm.nih.gov/edit2/index.html
- test `shouldParseFragment()` that should execute properly was introduced with commit c4105a0eeb6e35efe2319cfc27cdbfcff9577868

**Comment by cleberecht** [comment]
should be fixed in commit 6b44426

**Comment by fkaiserbio** [comment]
- tested and works
