### ISSUE TITLE
InChIKeyProviderTest.fetchWithPubChem() never terminates

### ISSUE THREAD

**Issue by fkaiserbio** [singa-bio/singa#87]
- there seems to be some infinite loops in the tests `InChIKeyProviderTest.fetchWithPubChem()` and `PubChemParserServiceTest.shouldResolveInChIKey()`
- disabled them for now
- please fix in branch `development`

**Comment by fkaiserbio** [comment]
fixed by merging with `develop/simulation`

**Comment by cleberecht** [comment]
was just about to comment that this was fixed in 6b10820
