### ISSUE TITLE
Ligands parsed by LigandParserService and PDB HETID show wrong connectivity

### ISSUE THREAD

**Issue by fkaiserbio** [singa-bio/singa#92]
- steps to reproduce:
```java
LeafSubstructure<?> atp = LigandParserService.parseLeafSubstructureById("ATP");
MoleculeGraph moleculeGraph = MoleculeGraphs.createMoleculeGraphFromStructure((OakLeafSubstructure<?>) atp);
```
  - open molecule in `GraphViewerPlayground.java`
  - several atom connections missing

**Comment by cleberecht** [comment]
commit 9e906b3 should fix the problem

seems that pdb has changed something in their ligand cif format, let me know if this works for you

**Comment by fkaiserbio** [comment]
- connectivity restored, thank you!
