### ISSUE TITLE
RCSB CIF file parsing fails

### ISSUE THREAD

**Issue by fkaiserbio** [singa-bio/singa#94]
It seems that RCSB has updated the definition for CIF files. Multi line entries might occur, see e.g.: http://files.rcsb.org/ligands/view/5MU.cif

```
_chem_comp.id                                    5MU 
_chem_comp.name                                  
;5-METHYLURIDINE 5'-MONOPHOSPHATE
;
_chem_comp.type                                  "RNA LINKING" 
```
This breaks a lot of structure parsing functionality. Key is the method `CifFileParser#extractValue` and how the parser extracts values from CIF files in general.

**Comment by cleberecht** [comment]
Thanks for pointing that out. I will have a look at it.

**Comment by cleberecht** [comment]
Exceptions be fixed for now, but there might still be problems with multi line names of ligands. Afik the name of ligands is not required for processing so this will be fixed later.

**Comment by JonStargaryen** [comment]
Just use `ciftools-java` for all your parsing needs :p

**Comment by cleberecht** [comment]
Hey Sebastian, we will properly adopt ciftools in an upcoming release for mmcif file parsing and also migrate current ligand handling. The latest commit to development should hotfix the problem for now.
All the Best :)
